/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

#define GPIOAEN (1U << 0)
#define GPIO_PIN_6 (1U << 6)
#define LED_PIN GPIO_PIN_6

int main(void)
{

    // Enable clock access GPIOA
    RCC->AHB1ENR |= GPIOAEN;

    // Set PA6 to output mode
    GPIOA->MODER |= (1U << 12);
    GPIOA->MODER &= ~(1U << 13);
    /* Loop forever */
    while (1)
    {
        /* code */
        GPIOA->ODR ^= LED_PIN;

        for (int i = 0; i < 100000;i++)
        {
            
        }
    }
}
