/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include "adc_dma.h"

/*
STM32F4: Single adc module, other like H7 has two adc modules(dual mode)
ADc Independent Mode: 
1. Single chanel - Single conversion
2. Multichannel(scan) - Single conversion mode
3. Single chanel, continuous conversion mode
4. Multichannel, continuous conversion mode
5. Injected continuous conversion mode

* Modules different channel: one module has 16 channels

1. Simplest ADC mode: ADC perform a single conversion of a single channel x-> stop after conversion is complete
2. Used to convert multiple channels successively: Up to 16 different channels with different sampling times can be converted in the stm32f4: Start --> Chx--->CHn-->Stop
3. Works in the background without intervention from CPU:  
     Start ----> CHx------> Continuously
4.
5. 
*/
int main(void)
{

    adc_dma_init();
    /* Loop forever */
    while (1)
    {

    }
}
